### ISSUE TITLE
Pair With Code - Kode Tidak Muncul

### ISSUE THREAD

**Issue by pa7rickr** [DikaArdnt/wajs#1]
Saya mencoba pair pakai code tetapi code-nya tidak muncul? Apakah ada solusi?

Kode saya:
```javascript
................
.......................................
const conn = new Client({
        playwright: {
            headless: true,
            args: ['--no-sandbox', '--disable-setuid-sandbox']
        }, 
        takeoverOnConflict: false, // If another whatsapp web session is detected (another browser), take over the session in the current browser
        takeoverTimeoutMs: 0,
        pairingNumber: "6283816xxxxxx",
        syncAllStatus: false,
        sessionName: 'session'
    })
    
    if (conn) { 
    	spins.add('spinner-1', { text: "Initializing browser..." })
        await sleep(10000) 
        spins.succeed('spinner-1', { text: `Using browser folder: '${__dirname}/session/session` })
        spins.add('spinner-2', { text: "Checking Authentication..." })
    }
    
    conn.initialize().catch((_) => console.log(_))
        conn.on("code", code => {
        	console.log(code)
            spins.update('spinner-2', { text: "Please insert this code.    " + code })
        })
 
...............................
....................
```

![issue_pairing_code_wajs](https://github.com/DikaArdnt/wajs/assets/77839637/e084dbf8-ef92-4951-b1f1-ae85cb3c15b3)

**Comment by DikaArdnt** [comment]
> Saya mencoba pair pakai code tetapi code-nya tidak muncul? Apakah ada solusi?
> 
> Kode saya:
> 
> ```js
> ................
> .......................................
> const conn = new Client({
>         playwright: {
>             headless: true,
>             args: ['--no-sandbox', '--disable-setuid-sandbox']
>         }, 
>         takeoverOnConflict: false, // If another whatsapp web session is detected (another browser), take over the session in the current browser
>         takeoverTimeoutMs: 0,
>         pairingNumber: "6283816xxxxxx",
>         syncAllStatus: false,
>         sessionName: 'session'
>     })
>     
>     if (conn) { 
>     	spins.add('spinner-1', { text: "Initializing browser..." })
>         await sleep(10000) 
>         spins.succeed('spinner-1', { text: `Using browser folder: '${__dirname}/session/session` })
>         spins.add('spinner-2', { text: "Checking Authentication..." })
>     }
>     
>     conn.initialize().catch((_) => console.log(_))
>         conn.on("code", code => {
>         	console.log(code)
>             spins.update('spinner-2', { text: "Please insert this code.    " + code })
>         })
>  
> ...............................
> ....................
> ```
> 
> ![issue_pairing_code_wajs](https://private-user-images.githubusercontent.com/77839637/293733605-e084dbf8-ef92-4951-b1f1-ae85cb3c15b3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NDUwMjcsIm5iZiI6MTcwNDU0NDcyNywicGF0aCI6Ii83NzgzOTYzNy8yOTM3MzM2MDUtZTA4NGRiZjgtZWY5Mi00OTUxLWIxZjEtYWU4NWNiM2MxNWIzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDEyMzg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NTUzYTdmMjEyOGY2YWQ5NzExYTZmOWU3YmFhNTliODdlOTA0ZTg0MzFmMDgyNTQ0YjAwMTc4MjZkNGUxYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EmSH90XpdpDJKV5SSqeLPFNcLr8ZU3xyYSHaNkVyPac)

untuk saat ini belum ada solusi untuk code pair tidak muncul saat mode headless, tapi kalo kamu menggunakan windows coba matikan headless

**Comment by pa7rickr** [comment]
> > Saya mencoba pair pakai code tetapi code-nya tidak muncul? Apakah ada solusi?
> > Kode saya:
> > ```js
> > ................
> > .......................................
> > const conn = new Client({
> >         playwright: {
> >             headless: true,
> >             args: ['--no-sandbox', '--disable-setuid-sandbox']
> >         }, 
> >         takeoverOnConflict: false, // If another whatsapp web session is detected (another browser), take over the session in the current browser
> >         takeoverTimeoutMs: 0,
> >         pairingNumber: "6283816xxxxxx",
> >         syncAllStatus: false,
> >         sessionName: 'session'
> >     })
> >     
> >     if (conn) { 
> >     	spins.add('spinner-1', { text: "Initializing browser..." })
> >         await sleep(10000) 
> >         spins.succeed('spinner-1', { text: `Using browser folder: '${__dirname}/session/session` })
> >         spins.add('spinner-2', { text: "Checking Authentication..." })
> >     }
> >     
> >     conn.initialize().catch((_) => console.log(_))
> >         conn.on("code", code => {
> >         	console.log(code)
> >             spins.update('spinner-2', { text: "Please insert this code.    " + code })
> >         })
> >  
> > ...............................
> > ....................
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![issue_pairing_code_wajs](https://private-user-images.githubusercontent.com/77839637/293733605-e084dbf8-ef92-4951-b1f1-ae85cb3c15b3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NDUwMjcsIm5iZiI6MTcwNDU0NDcyNywicGF0aCI6Ii83NzgzOTYzNy8yOTM3MzM2MDUtZTA4NGRiZjgtZWY5Mi00OTUxLWIxZjEtYWU4NWNiM2MxNWIzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDEyMzg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NTUzYTdmMjEyOGY2YWQ5NzExYTZmOWU3YmFhNTliODdlOTA0ZTg0MzFmMDgyNTQ0YjAwMTc4MjZkNGUxYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EmSH90XpdpDJKV5SSqeLPFNcLr8ZU3xyYSHaNkVyPac)
> 
> untuk saat ini belum ada solusi untuk code pair tidak muncul saat mode headless, tapi kalo kamu menggunakan windows coba matikan headless

Terimakasih solusi dan responnya 🙏
